version: '3'

networks:
  statista-challenge:

services:
  postgres:
    image: postgres:latest
    container_name: statista-challenge-postgres
    networks:
      - statista-challenge
    env_file:
      - .env
    restart: always
#    volumes:
#      - type: bind
#        source: ./db_init.sh
#        target: /docker-entrypoint-initdb.d/db_init.sh
#        read_only: true


  app:
    image: statista-challenge:latest
    container_name: statista-challenge-app
    networks:
      - statista-challenge
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    build: ./
#    restart: always
    working_dir: /app
    command: python -m http.server 8080 --directory ./