version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: statista-challenge-postgres
    env_file:
      - .docker.env
    restart: always
#    ports:
#      - "5432:5432"

  app:
    image: statista-challenge-app:latest
    container_name: statista-challenge-app
    env_file:
      - .docker.env
    depends_on:
      - postgres
    restart: always
    ports:
      - "8181:8181"
#    volumes:
#      - ./data/:/app/data
    build: ./
    working_dir: /app
