version: '3'

networks:
  statista-challenge-network:

services:
  postgres:
    image: postgres:latest
    container_name: statista-challenge-postgres
    networks:
      - statista-challenge-network
    env_file:
      - .env
    restart: always

  app:
    image: statista-challenge:latest
    container_name: statista-challenge-app
    networks:
      - statista-challenge-network
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    build: ./
#    restart: always
    working_dir: /app
    command: python -m http.server 8080 --directory ./
