version: '3'

networks:
  statista-challenge-network:

services:
  postgres:
    image: postgres:latest
    container_name: statista-challenge-postgres
    networks:
      - statista-challenge-network
    env_file:
      - .docker.env
    restart: always
#    ports:
#      - "5432:5432"

  app:
    image: statista-challenge-app:latest
    container_name: statista-challenge-app
    networks:
      - statista-challenge-network
    env_file:
      - .docker.env
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
#    volumes:
#      - ./data/:/app/data
    build: ./
    working_dir: /app
